language: node_js
before_script:
- npm run setup
- npm run build
node_js:
- 14
deploy:
  app: react-app-task-timer
  provider: heroku
  api_key:
    secure: gVhNu0l/sBzrSz9l7n6CkFBB97o15gd0IfE1iThF1xZS1dayhHR8HZczT0hPRvD3bGJNaS5kIO4urNHvq8qIK3MNU/6p9w8opMvVydA+r4oPBLiQLm4iPPzw2RPebxaZxu7liTCrYGgEtkfvdscQ1pwlj+O7RppiTibkDYTy9ThwkA3nhuzUC5uZPAgI8fAe75mebs3tloxCRhUUXQ1H9ATieGY5bu8HJv868AzaGgRwndjRDmSNFLtr90h4sgzXjCfAT2VZiWoaku+E+mTFELGFsI7xCAbD3QvywsZvFVkCaBCK2crAgSAeQaekl16mIbtwuomCSBr7G5qRPIMibB7TZgd2N+iefC5aoc/71Ogldzbt8MD/XkkvmgbPYzbrrbrwKykdjpn6BmSzg/IErYnoy6114oJVFw7ebQwZQjVotjEaDUROWxgK9ZxDUDpw/ZyO6k5xHZgxvU2dfIr7FzhYhabJg/plcr1T88ZbioUDBVhPThgkJbBH3x8h2uhh6YuqsNSL/5sBWm/g3amJfIS3ktlQ4b2rDWOjIkzxeKM+VcBePc9sWnfnvydFPdrQZE1yWT28TbGMfkyYKao8ViEFv3p3B9Bhbh/KFyDUtydXekKXCtOG5UXeNqLQ5c2SrO0uJjWu3S90DaYG7cvoKdl8a/cPdJs/Mzli4L2WTfM=
